### ISSUE TITLE
Trouble running backend without GUI/Tkinter

### ISSUE THREAD

**Issue by MemduhG** [michmech/lexonomy#314]
**Describe the bug**
Tkinter seems to be needed to run this, even when it's just the backend. Perhaps I am making a mistake. Here is the command I ran and the output it gave me:

```bash
$ python lexonomy.py
Traceback (most recent call last):
  File "/root/lex/lexonomy/website/lexonomy.py", line 9, in <module>
    import ops
  File "/root/lex/lexonomy/website/ops.py", line 25, in <module>
    from icu import Locale, Collator
  File "/root/lex/venv/lib/python3.11/site-packages/icu/__init__.py", line 3, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```

**To Reproduce**
1. SSH to a server with no visual output
2. Clone the repo
3. Install the python dependencies with pip
4. Run with `python3 lexonomy.py`

**Expected behavior**
I would have expected the backend to start up so I could access it from another machine.

**Environment**
 - Digitalocean droplet running Ubuntu 23.10 x64
 - Python 3.11.6
 - versions of the installed modules:
```
 $ pip freeze
beautifulsoup4==4.12.2
cffi==1.16.0
cryptography==41.0.5
icu==0.0.1
jwt==1.3.1
lxml==4.9.3
Markdown==3.5
pycparser==2.21
soupsieve==2.5
typing_extensions==4.8.0
```

**Comment by memduh-gokirmak** [comment]
Had the wrong package name for ICU, they explain things on their git website here: https://gitlab.pyicu.org/main/pyicu

What worked for me was:
```
apt-get install pkg-config libicu-dev
pip install --no-binary=:pyicu: pyicu
```

**Comment by MemduhG** [comment]
Had the wrong package name for ICU, they explain things on their git website here: https://gitlab.pyicu.org/main/pyicu

What worked for me was:

```
apt-get install pkg-config libicu-dev
pip install --no-binary=:pyicu: pyicu
```
